### ISSUE TITLE
write tests for `/database/queries.js` and `/database/commands.js`

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/curriculum-app#376]
do your best to test them as well as you can

**Comment by jrpool** [comment]
Are we aware that the production curriculum is no longer recording new skill checks in the database? database/commands.setSkillCheck is running knex.insert, but nothing gets inserted into skill_checks. This ticket is to test, not to fix, so I wondered.

**Comment by jrpool** [comment]
The broken feature is apparently the same as reported in “Checks disappearing on skills list (#124)”, which was closed in July but recurred in September. I am investigating it and have sent a message to P1, P2, and P3 in Slack warning them not to mark skills until the feature is repaired. Until told otherwise, I am treating this issue as covering the broken feature, since complete testing is not possible on a broken feature.

**Comment by jrpool** [comment]
I have submitted PR 381 that repairs the bug. I’ll proceed with the development of tests.

**Comment by judytuna** [comment]
Putting in links to make use of Github's organizational messages.
- @jrpool's bug fix as mentioned above: https://github.com/LearnersGuild/curriculum/pull/381 
- @jrpool's tests: https://github.com/LearnersGuild/curriculum/issues/376
- @kelceywilson's bug report: https://github.com/LearnersGuild/curriculum/issues/382

**Comment by jrpool** [comment]
[PR 386](https://github.com/LearnersGuild/curriculum/pull/386) is intended to resolve this issue.
